### ISSUE TITLE
What about Platforms?

### ISSUE THREAD

**Issue by aaronpowell** [Readify/madskillz#10]
In #9 @kjacobsen makes a good point about how what is written down thus far related to the support team and that got me thinking about Platforms and how this relates to them.

Looking at what we have in the matrix thus far there's a lot of points that I'm not sure are directly relatable to Platforms, so would it make sense to have them go through the same list? Would we have a separate list?

**Comment by RobFaie** [comment]
Since Platforms hasn't existed for a year now, shall we close this?
