### ISSUE TITLE
Tone of Engineering pathway

### ISSUE THREAD

**Issue by MehdiK** [Readify/madskillz#109]
I see a bit of ego in the [engineering pathway](https://github.com/Readify/madskillz/blob/master/Engineering.md). Here's a few examples of that and why I think it's not right:

> I am a greatly desired team member for Readify projects.

While I like this mantra, I am not sure it's placed properly (it's currently under I am known for my technical knowledge). I feel that this depends more on the attitude than what we know and I hope we all fit into this category. In that sense, this is already captured under [egoless, team oriented developer](https://github.com/Readify/madskillz/blob/master/Development.md#i-am-an-egoless-team-oriented-developer-1): "_Other team members genuinely want me on their team_"

> I am more than a Senior Developer

No one is more than others. The language should change to focus on the Senior Engineer's capabilities as opposed to how they compare to a different role. Created #108 to deal with this.

> I have the skills, speed and knowledge that enable me to consistently be one of the most productive team members of any team I am part of.

Being or wanting to be the most productive team member is a self-centric perspective. Instead of this I'd like to see a team member focus on making their team a really productive team. As an SE, that could happen through better technology and design choices.

> People want to work on engagements with me because they know I will help them grow their technical capabilities.

We have a similar sentence [in LC](https://github.com/Readify/madskillz/blob/master/Development.md#i-am-becoming-a-respected-and-trusted-leader-of-people), `People want to work on engagements with me because they know they'll be richer for the experience and I will help them grow`, which I think is not right either. Instead of saying people want to work on engagements with me, we should focus on the contribution the individual makes to the team; e.g. "_I help my team members grow their technical capabilities._". The likely outcome of this giving attitude is that people will want to work with this individual; but this shouldn't be the goal or the mantra.

**Comment by andrewabest** [comment]
Issue seems to have gotten its wires crossed with the merge of a couple of PRs, closing it off as it has been addressed in the above two PRs.
