### ISSUE TITLE
Syncing with MyCareer

### ISSUE THREAD

**Issue by rbanks54** [Readify/madskillz#25]
With our people team now using MadSkillz as the official retro/performance review tool they will effectively be taking a snapshot of an evolving document each quarter.

We need a way to track this and see what was current as at a point in time.  With that in mind, I've added a tag to the repo for the version used for the May 2015 snapshot.

I'm assuming this is sufficient, but if you think we should also be using Milestones, Releases or some of GH method to track the snapshots then shout it out in the comments and we'll have a look at it.

**Comment by andrewabest** [comment]
MyCareer is dead 👍
