### ISSUE TITLE
SD - setting technical direction

### ISSUE THREAD

**Issue by rbanks54** [Readify/madskillz#26]
> I am comfortable setting technical direction for brown-fields product, reducing technical debt

Given setting technical direction is usually only done for green fields or major rewrite projects, how about we reword this slightly as the following
- I am comfortable improving brown fields products by tweaking technical approaches, introducing design patterns and reducing technical debt as appropriate

Would that work better? Or do you have other improved wording that might hit the mark better?

**Comment by WillRay** [comment]
@rbanks54 is this issue still relevant? It looks like changes over the years have addressed this.

In particular, these three bullet points seem to tackle it:

> #### I am trusted to ship full products (or vertical slices of larger products) from idea to production.
> - I am proficient at qualifying and reducing technical debt.
> - I am comfortable determining technical direction within brown-fields projects.
> - I know how to make pragmatic decisions in order to ship a product.

**Comment by rbanks54** [comment]
@WillRay Hmmm... maybe if all three are taken together, but the separated nature of the points makes it easy to focus only on one item at a time

**Comment by rbanks54** [comment]
That said, I'm happy to let this one lapse now. I'll close the issue.
