### ISSUE TITLE
Levelling up with madskillz

### ISSUE THREAD

**Issue by andrewabest** [Readify/madskillz#34]
Quoting @robdmoore from https://github.com/Readify/madskillz/issues/32#issuecomment-113974396
> With respect to promotions, I think that given that the consultants are the ones having a collaborative dialogue and peer-reviewed contribution process I feel mad skillz is an excellent description of what it means to be in each role! There is one problem I see in the way we currently do it though - we rank against your current level and wait until you are outstanding or no brainer in everything. I think it makes much more sense to combine this with a rating against the next level - Id expect someone that wants a promotion to be stepping outside their current role and be at a maturing on at least some of the next level.

I thought we could briefly discuss this, and perhaps move to amend one of the readme files to include this use case once we come to a consensus. 

How I have been assessing myself coming in to my retrospectives is both against SC *and* LC, which very much aligns with what you describe @robdmoore. Have other people been doing this? Does everyone agree that this is an appropriate approach? I think that in this case a bit of crystal ball gazing is a good thing to help set your long-term course.

**Comment by bendetat** [comment]
Agreed, I kind of assumed that this would be the case. The SC mad skillz have definitely helped me looking forward.

Would be good to have this come up in retros too, so maybe this is something that should be discussed between the retro-ee and the retro-er ahead of time?

**Comment by c0ntinuum** [comment]
> Have other people been doing this?

I have been. As an exercise I rated against _all_ the **Mad Skillz** levels.

> I think that in this case a bit of crystal ball gazing is a good thing to help set your long-term course.

Agreed. All Readafarians have skills outside of their "employment level".

**Comment by tathamoddie** [comment]
The process at https://readify.sharepoint.com/the-way-we-work/Pages/Retro.aspx currently calls out the idea of comparing with the role above if aiming for promotion. I am currently running under the view that this repo is the content, not so much the processes (retros being one of many).

**Comment by mjhilton** [comment]
I've been doing this.
It was the approach I used with the old S&B matrix, so I just naturally did the same with MadSkillz... Only difference being that MadSkillz is a much more tangible and useful benchmark than the old way :grinning:

**Comment by andrewabest** [comment]
Sounds like most of us have been doing this anyway :) Perhaps we could elaborate on it a little in the Retro page in sharepoint then? @bendetat and @aaronpowell had some good suggestions in the PR that it would be nice to incorporate.

**Comment by andrewabest** [comment]
After an offline chat with @tathamoddie we came to the consensus of:

* Things that pertain to *the usage* of Madskillz belong in the Madskillz repository, so that they can be collaborated on by the consultants. Many things use Madskillz, the retro process being one of them.
* Things that pertain to *the definition* of the retro process belong in Readdit.

With that being said, we will continue to collaborate on the attached PR :)

**Comment by rbanks54** [comment]
I'm not quite sure where the confusion about promotions has come from.

Promotion is gated as follows:
* To be considered for a promotion you need to be successfully doing your current role.
* To receive a promotion you have to show sufficient skills and behaviours that there is confidence you will be successful in the target role.

This is no different to what has been in place for many, many years.

**Comment by andrewabest** [comment]
@rbanks54 it was probably just the question of how that applies to madskillz - most seem to have been doing it as you have described, but the fact it was raised by @robdmoore demonstrates we should probably have it down in writing alongside madskillz.

Thanks for the link to the promotions page too :) I hadn't read it yet.

**Comment by andrewabest** [comment]
Merged in with https://github.com/Readify/madskillz/pull/35
