### ISSUE TITLE
What does "unconventional value" mean?

### ISSUE THREAD

**Issue by cottsak** [Readify/madskillz#41]
Re: https://github.com/Readify/madskillz/blob/master/Consulting.md section "Senior Consultant".

What does "unconventional value" mean? I can't see where it's explained. So in that sense it's a waste and serves to complicate and confuse the definition.

Should we remove it?

**Comment by kjacobsen** [comment]
If we can't define it, then it is hard to explain to a new starter or an outsider. I agree that we need to think about removing it.

**Comment by andrewabest** [comment]
It is another take on the "with velocity and uncommon sense" tagline seen on Readify.net. The intent of the statement that Senior Consultants embody Readify's value proposition(s).

**Comment by cottsak** [comment]
@andrewabest "with velocity and uncommon sense" sounds like a great pr/marketing-ese line, however such ambiguous and bombastic expressions have no place in madskillz IMO. We need clearly defined parameters here.

**Comment by andrewabest** [comment]
@cottsak - it is part of the 'position statement' for SC, not part of what is intended to be measurable criteria. It should be something you identify with as someone looking to grow into the position or as someone who currently embodies the position. 

I agree that if you don't know what it means that it would make it hard for you to connect with the statement, but I think a little bit of expressiveness in these 'Position statements' is not out of question - they should be motivational and inspirational. 

Do you have a suggested alternate wording that captures the intent of the statement more clearly?

**Comment by andrewabest** [comment]
To quote the Madskillz wiki
> I want to use language people can identify with, more human than human resources.

**Comment by cottsak** [comment]
@andrewabest No I don't at this time. My intention with this issue was "trimming the fat".

I still find it difficult to connect with the "embodiment" of SC from these statements. I'm here to try and learn what it means so that I can strive for it perhaps. However, until I understand it, I can't know whether it's for me or even something within my reach. So, cutting away the 'fruit' (/fat?) seems like a worthy cause if it's going to make these definitions easier to digest I think.

**Comment by liammclennan** [comment]
It means that we don't see Readify as yet another mediocre consultancy and that SCs should reflect that.

**Comment by danieljanczak** [comment]
Liam, maybe we should write just that, literally: "We are not yet another mediocre consultancy and SC should reflect that". Anything that avoids bombastic language is good. If there is any thing in which mediocre consultancies excel, it's bombastic statements. We are better than this.

**Comment by cottsak** [comment]
@danieljanczak that's kinda what i've suggested in this PR https://github.com/Readify/madskillz/pull/42/files

**Comment by andrewabest** [comment]
I'm not entirely sure if this is the sort of messaging we want to put out - this is a public repository, and reflects our values. The statement should be a positive affirmation of our drive to deliver exceptional value to our clients.

**Comment by andrewabest** [comment]
Would removing the word 'unconventional' be enough to satisfy closing this issue? "I represent the value Readify brings to the market". We don't need to define what that value is in here - we have other locations for that, such as http://readify.net/services/apps-development/ or perhaps even https://readify.sharepoint.com/the-way-we-work/Pages/Readify%20Values.aspx (although this page is fairly bare at the time of posting)

**Comment by robdmoore** [comment]
+1 to andrew

--

**Comment by cottsak** [comment]
@andrewabest how about https://github.com/Readify/madskillz/pull/43 then? Is that link going to stick around?

**Comment by robdmoore** [comment]
I think calling out *just* that link is too explicit - there are so many other services we provide than just that.

What about http://readify.net/services?

**Comment by cottsak** [comment]
@robdmoore Care to start a PR? Looks like we're at that time now. ;-)

**Comment by robdmoore** [comment]
Sorry I don't have time to.

**Comment by andrewabest** [comment]
My proposal is here https://github.com/Readify/madskillz/pull/44

**Comment by cottsak** [comment]
Copying my comment from https://github.com/Readify/madskillz/pull/44 for completeness:

> I'd prefer the doc not to link externally also. I think it holds more value being self contained.

> However on your second point @andrewabest, "If people don't know what our values are", I strongly object to this. Readify "values" should not be some ambiguous, etherial concept. They should be clear. If you want to say that a SC represents Readify's 'value', then you need to say what that value is.

**Comment by kjacobsen** [comment]
Perhaps we could talk about the value we bring at all levels to the market? Move this from SC to Developer? We all bring "unconventional" value.

**Comment by danieljanczak** [comment]
I think that clients just expect "value". It doesn't have to be "uncoventional". It just have to exist. If we provide value this is already much more than many other consultancies.

**Comment by cottsak** [comment]
@danieljanczak Good point. The "unconventional" only serves to confuse everyone I think. It doesn't add any value (pardon the pun).

**Comment by random82** [comment]
Not relevant anymore. Closing.
