### ISSUE TITLE
What does "richer experience" mean?

### ISSUE THREAD

**Issue by Meligy** [Readify/madskillz#53]
https://github.com/Readify/madskillz/blame/master/Consulting.md#L53

> - I can tactfully challenge and coach people and have them leave **richer for the experience.**

I think I remember a couple of PCs suggest this highlighted part is due for a change. I'm not sure what's suggested to replace it thugh.

**Comment by houratious** [comment]
Does it mean something like this? 
I can tactfully challenge and coach people and introduce them to new knowledge, be it additional information or the same information in a new perspective.

**Comment by mishrsud** [comment]
@Meligy @WillRay looks like the changes pertaining to this issue are merged, does this issue still have a need to be open?
