### ISSUE TITLE
Engineering Branch and Team management

### ISSUE THREAD

**Issue by kjacobsen** [Readify/madskillz#66]
How do we feel about handling those Senior Engineers who also need to manage a team (much like a TL/LC)? How do we review the skills required?

**Comment by liammclennan** [comment]
Doesn't that make them an SC?

**Comment by kjacobsen** [comment]
What if they are not customer facing?

**Comment by aaronpowell** [comment]
Still think they are an SC if they are leading a team, regardless of whether it's customer facing or not.

**Comment by kjacobsen** [comment]
Thanks, I will close this one off.
