### ISSUE TITLE
Engineering community engagement

### ISSUE THREAD

**Issue by andrewabest** [Readify/madskillz#73]
In the old Skills and Behaviours Matrix, there was an item in it that was quite polarizing, with most people not liking it - it spoke of building your 'personal brand'. To some this was :rainbow:, and to others it was :skull:. 

During a retro with @tristanmenzel, one of our QLD SE's, I noticed that under https://github.com/Readify/madskillz/blob/master/Engineering.md#i-am-known-for-my-technical-knowledge is an item that states: 

> I have community engagement.

This is very similar to the old 'personal brand' statement. Some people don't like presenting. Some people don't have the time to invest in presenting.

One of the things we tried to do when creating Madskillz was to move away from these potentially polarizing statements, and move towards saying things that could have wider applicability, where appropriate. So 'personal brand' became 'investing in Readify' https://github.com/Readify/madskillz/blob/master/Consulting.md#i-am-investing-back-into-readify.

I'm wondering if we should be change the focus of this point to how our Senior Engineers invest their considerable technical wisdom back into Readify - whether that be via community engagement or internal engagement via workshops, Slack, Yammer, tech@, or even their own teams (brownbags etc).

Thoughts?

**Comment by robdmoore** [comment]
Sounds fair to me...

**Comment by kjacobsen** [comment]
I had wondered about that one too. I agree that we need to rethink that line.

Perhaps we can take some of the content from SC around reinvesting back into Readify?

**Comment by halkar** [comment]
Can we have both? Some Engineers can share their knowledge outside as well as inside Readify.

**Comment by andrewabest** [comment]
That is what I was suggesting in my initial post @halkar 

> whether that be via community engagement or internal engagement via workshops, Slack, Yammer, tech@, or even their own teams (brownbags etc)

Specifically the "Community engagement" part. So it is more about that they are reinvesting somehow, via external or internal engagement.

**Comment by halkar** [comment]
Oh, sorry @andrewabest , I'm not a very good reader though.

**Comment by WillRay** [comment]
@andrewabest is the "I contribute to open source projects." a polarizing topic as well? (For the same reasons?)

Borrowing a bit from the SC role (as @kjacobsen mentioned), we could change the wording to describe _what_ we want, not _how_ it should be done. What do you think about this?

> #### I am known for my technical knowledge
> - I am sharing my on-the-job learning and experiences with others so they can be more effective in their roles.
> - I am actively involved in helping guide others through tough technical challenges.
> - I am a greatly desired team member for Readify projects.

**Comment by robdmoore** [comment]
One thing ot keep in mind that the list are "examples" they aren't a definitive list of what to do. Some will apply to some people in a role and not others.

(Not saying the suggestion isn't valid, because what you just suggested reads well, just want to make sure we keep the above in mind).

**Comment by bplowry** [comment]
@robdmoore Given that this stuff feeds into retros as a "requirement", it doesn't necessarily come across as an example of something that you _could_ do, and could easily be interpreted as _you must do this_.

**Comment by robdmoore** [comment]
What makes you say they feed in as a "requirement"?

**Comment by bplowry** [comment]
Discussed offline. As you mentioned README.md shows 
> It seeks to describe some *defining characteristics* about each role, and provide some concrete *examples* along the way.
