### ISSUE TITLE
Data and Analytics roles

### ISSUE THREAD

**Issue by jarvisrob** [Readify/madskillz#82]
I've been asked to assemble the Mad Skillz roles for Data and Analytics. This was mentioned in the latest Exec meeting summary, about 1/2 to 2/3 way down the list:
https://www.yammer.com/readify.net/#/Threads/show?threadId=859425484

**Comment by jarvisrob** [comment]
D&A roles written, modified for content from Consulting roles. Have been reviewed by both Dir D&A (Leah) and People Dir (Michelle). Merged into master. Issue closed.

**Comment by random82** [comment]
Good job mate! Thanks for that
