### ISSUE TITLE
What about Support?

### ISSUE THREAD

**Issue by kjacobsen** [Readify/madskillz#9]
I don't want to start a turf war, but how do we integrate the support team with these descriptions?

One reason I ask is that we have been talking about more "formalized" descriptions. There is quite an interesting overlap in what I have read here and with what we do in support. 

As you may (or may not know), the team consists of Technical Leads, Senior Sustained Engineering Developers, and Sustained Engineering Developers. Linking a three tier structure with a 5 tier structure could be an interesting challenge. There are a number of advantages (in terms of progression, training etc).

I will ask Shweta and Mahesh to take a look at the excellent work here, but would like to hear some ideas.

**Comment by kjacobsen** [comment]
I think we can now close this one.

**Comment by andrewabest** [comment]
Done.
