### ISSUE TITLE
Should egoless, team-oriented developer be highlighted for SD?

### ISSUE THREAD

**Issue by robdmoore** [Readify/madskillz#92]
@grahamlea pointed out on twitter that phrase should probably be more prominent in the SD description (https://twitter.com/evolvable/status/946673944550969344).

On one hand, we could say each role is a superset of the previous, on the other you could say it’s a super important part of the SD role so should be highlighted.

Thoughts?

**Comment by AdrianJSClark** [comment]
In the SD description the _"I am an egoless, team oriented developer."_ item changes to:

- I am a supporter of my team and my customer.

The "egoless, team-oriented developer" is a fantastic description. If we were to change it to be more like the first, we'd need to include the support of the customer.

The closest suggestion I could come up with is:

- I give support to both my team and my customer without ego.

But I'm sure that someone else could improve on my attempt.

**Comment by robdmoore** [comment]
What about I’m an egoless developer who supports my team and my customer?

—

On 29 Dec 2017, at 8:33 pm, Adrian Clark <notifications@github.com<mailto:notifications@github.com>> wrote:


In the SD description the "I am an egoless, team oriented developer." item changes to:

  *   I am a supporter of my team and my customer.

The "egoless, team-oriented developer" is a fantastic description. If we were to change it to be more like the first, we'd need to include the support of the customer.

The closest suggestion I could come up with is:

  *   I give support to both my team and my customer without ego.

But I'm sure that someone else could improve on my attempt.

**Comment by ghuntley** [comment]
Ego is something that people too often mistaken as a bad thing. The formal definition of the word roughly translates as conscious of mind or being conscious of your own identity. I've run into plenty of folks who need _more_ ego (self-awareness to their behaviours).

Are we using the right language here?

**Comment by robdmoore** [comment]
I’d say that most uses of ego are in the negative sense. As per the internal ego blog post Matt and I wrote a few years back we need to be extra careful about that in a consultancy so I’d rather be more on the side of caution in this one.

**Comment by glav** [comment]
If we want to get really pedantic, I'd say finding an egoless person is almost impossible. We all have them.  So to be more precise, something like (much like Adrians), "I am a developer who is focused on the success of my team and my customer, without the need to boost my ego".

**Comment by robdmoore** [comment]
That’s fair :)

**Comment by cottsak** [comment]
I would agree with @ghuntley that an ego is a good thing and in my experience, a quality many of my past and present colleagues share.

What you don't want is an attitude, or communication style that pushes folks away and works against team spirit, self-improvement and healthy human relationships. I don't think you should label that "ego". The fact is that even when you have these types of "negative" behaviours, they're usually learnt and so can be unlearnt. I think Readify should be known as a place which brings great people together, who strengthen each other over time.
